name: example internal story upload action

on: 
  push:
    paths:
      - 'github/workflows/example_internal_publish.yaml'
      - '_site/**'

jobs:
  story-upload-dev:
    name: story upload
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: navikt/story-upload@v1
        with:
          id: 8e2c1d8f-4148-4165-a101-ce27a1cc609e
          dir: example/quartobook/output
          team_token: ${{ secrets.TEAM_TOKEN }}
          env: dev
  story-upload-prod:
    name: story upload prod
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - uses: navikt/story-upload@v1
          with:
            id: 0f5cc968-ddc8-47ec-816a-763059d25ae1
            dir: example/quartobook/output
            team_token: ${{ secrets.TEAM_TOKEN_PROD }}
            env: prod
